### ISSUE TITLE
[Error] TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by powermew** [NickShahML/tensorflow_with_latest_papers#21]
Hi. I downloaded dataset and excute below code.

**python ptb_word_lm.py --data_path=simple-examples/data/**

After that, this error showen up.

**TypeError: Expected int32, got list containing Tensors of type '_Message' instead.**

Here is my full error message.
And i am using tensorflow 1.2.0, python 2.7, Ubuntu 16.04
Anybody can help me?

2017-10-19 02:51:37.532832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-10-19 02:51:37.532835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-10-19 02:51:37.532840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0)
WARNING:tensorflow:Using Kronecker Reparmeterization on Highway RNN Cell
Traceback (most recent call last):
  File "ptb_word_lm.py", line 335, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 312, in main
    m = PTBModel(is_training=True, config=config)
  File "ptb_word_lm.py", line 137, in __init__
    (cell_output, state) = cell(inputs[time_step], state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 953, in __call__
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/home/powermew/neural_network/JKNN/tensorflow_with_latest_papers-master/rnn_cell_modern.py", line 52, in __call__
    use_kronecker_reparameterization=self._use_kronecker_reparameterization))
  File "/home/powermew/neural_network/JKNN/tensorflow_with_latest_papers-master/linear_modern.py", line 95, in linear
    res = tf.matmul(tf.concat(1, args), matrix)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by powermew** [comment]
Over tensorflow v 1.2.0, it should change like this
tf.concat(1, outputs)
-> tf.concat(outputs, 1)
